apiVersion: v1
kind: Namespace
metadata:
  name: openshift-controller-manager
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/run-level: "1"
    openshift.io/cluster-monitoring: "true"
