apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-controller-manager
  name: system:openshift:operator:openshift-controller-manager:public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:operator:openshift-controller-manager:public
subjects:
- kind: Group
  name: system:authenticated
